### ISSUE TITLE
Fails to match valid Authorization header

### ISSUE THREAD

**Issue by whitlockjc** [30x/microgateway-plugin-sso-proxy#17]
Per https://tools.ietf.org/html/rfc2617#section-1.2, the `Authorization` header can have `Bearer` or `bearer` but the current regex only matches one case.

**Comment by whitlockjc** [comment]
https://github.com/30x/microgateway-plugin-sso-proxy/issues/17

**Comment by mpnally** [comment]
BEARER and BeArEr are also valid - the string is case-insensitive.
